---
- name: patch the server
  hosts: all
  become: true
  tasks:
     - name: testing host
       debug: 
         var: config
         
     - name: testng guest
       debug:
         msg: "The value of my_variable is {{ config.name }}"
