---
- name: patch the server
  hosts: all
  become: true
  tasks:
     - name: testing host
       debug: 
         var: config

     - name: testing guest
       debug: 
         var: guest

        
