---
- name: Get sysName.0 via SNMPv3
  hosts: all
  task: 
    - name: ansible snmp.get 
      ansible.snmp.get:
      oids:
        - oid: "1.3.6.1.2.1.1.5.0"
      vars:
        ansible_connection: ansible.snmp.v3_usm
        ansible_snmp_host: "{{ ansible_host }}"
        ansible_snmp_usm_user: "user"
        ansible_snmp_usm_auth_protocol: "sha256"
        ansible_snmp_usm_auth_key: "{{ key }}"
        ansible_snmp_usm_priv_protocol: "aes"
        ansible_snmp_usm_priv_key: "{{ pass }}"
        ansible_python_interpreter: /usr/local/bin/python3
